"""
Report PDF Generator
Creates a clean interview report PDF using reportlab (platypus).
No system dependencies — pure Python, Render-friendly.
"""

import io
from datetime import datetime


def _safe(val, default="N/A"):
    if val is None or val == "":
        return default
    return str(val)


def _truncate(text, max_len=500):
    s = str(text or "")
    if len(s) > max_len:
        return s[:max_len] + "…"
    return s


def generate_pdf_report(candidate_data: dict, session_data: dict, ats_score: dict = None) -> io.BytesIO:
    """
    Generate a PDF report using reportlab and return BytesIO buffer.
    Sections:
    - Header: Candidate name, email, role, company, date
    - ATS Score (if available)
    - Interview Summary: total questions, avg scores
    - Skill Gaps / Recommendations
    - Per-question breakdown
    - Footer: Generated by ... + timestamp

    Safe defaults for missing fields.
    Returns io.BytesIO with PDF bytes (seek(0) done).
    """
    # Lazy import so module import never crashes if reportlab missing
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.styles import ParagraphStyle as PS
    except ImportError as e:
        raise ImportError(f"reportlab is required for PDF generation: {e}")

    candidate_data = candidate_data or {}
    session_data = session_data or {}
    ats_score = ats_score or None

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title="Interview Report",
        author="AI Interview Intelligence System",
    )

    styles = getSampleStyleSheet()
    # Custom styles
    s_title = PS("TitleCustom", parent=styles["Title"], fontSize=18, leading=20, textColor=colors.HexColor("#4f46e5"), spaceAfter=2)
    s_h1 = PS("H1", parent=styles["Heading1"], fontSize=13, leading=16, textColor=colors.HexColor("#1e293b"), spaceBefore=10, spaceAfter=6, borderPadding=(0, 0, 4))
    s_h2 = PS("H2", parent=styles["Heading2"], fontSize=11, leading=14, textColor=colors.HexColor("#334155"), spaceBefore=8, spaceAfter=4)
    s_body = PS("Body", parent=styles["BodyText"], fontSize=8.5, leading=11.5, textColor=colors.HexColor("#334155"), spaceAfter=3)
    s_small = PS("Small", parent=styles["BodyText"], fontSize=7.5, leading=10, textColor=colors.HexColor("#64748b"))
    s_cell = PS("Cell", parent=styles["BodyText"], fontSize=7.5, leading=9, textColor=colors.HexColor("#1e293b"))
    s_cell_small = PS("CellSmall", parent=styles["BodyText"], fontSize=7, leading=9, textColor=colors.HexColor("#475569"))

    story = []
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    # ── Header ──
    story.append(Paragraph("AI Interview Intelligence System", s_title))
    story.append(Paragraph("Interview Performance Report", PS("Sub", parent=s_body, fontSize=9, textColor=colors.HexColor("#64748b"), spaceAfter=4)))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=8))

    cand_name = _safe(candidate_data.get("name") or candidate_data.get("candidate_name"), "Candidate")
    cand_email = _safe(candidate_data.get("email") or candidate_data.get("candidate_email"), "N/A")
    cand_role = _safe(candidate_data.get("role") or candidate_data.get("candidate_role"), "N/A")
    company = _safe(candidate_data.get("company") or session_data.get("company") or candidate_data.get("candidate_company"), "General")
    date_str = _safe(session_data.get("created_at") or session_data.get("start_time") or now_str, now_str)

    header_data = [
        [Paragraph(f"<b>Candidate:</b> {_safe(cand_name)}", s_cell), Paragraph(f"<b>Role:</b> {_safe(cand_role)}", s_cell)],
        [Paragraph(f"<b>Email:</b> {_safe(cand_email)}", s_cell), Paragraph(f"<b>Company:</b> {_safe(company)}", s_cell)],
        [Paragraph(f"<b>Date:</b> {_safe(date_str)[:19]}", s_cell), Paragraph(f"<b>Session:</b> {_safe(session_data.get('session_id') or session_data.get('id'), 'N/A')}", s_cell)],
    ]
    t = Table(header_data, colWidths=[85*mm, 85*mm])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#e2e8f0")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
    ]))
    story.append(t)
    story.append(Spacer(1, 6))

    # ── ATS Score ──
    if ats_score and isinstance(ats_score, dict) and ats_score.get("score") is not None:
        story.append(Paragraph("ATS Resume Score", s_h1))
        score = ats_score.get("score", 0)
        try:
            score_int = int(score)
        except Exception:
            score_int = 0
        bd = ats_score.get("breakdown") or {}
        # Score badge line
        story.append(Paragraph(f"<b>Overall ATS Match:</b> {score_int}/100", s_body))
        # Breakdown table
        bd_rows = [
            [Paragraph("<b>Dimension</b>", s_cell), Paragraph("<b>Score</b>", s_cell)],
            [Paragraph("Skills Match", s_cell_small), Paragraph(f"{_safe(bd.get('skills_match'), 0)}/40", s_cell_small)],
            [Paragraph("Experience Keywords", s_cell_small), Paragraph(f"{_safe(bd.get('experience_keywords'), 0)}/20", s_cell_small)],
            [Paragraph("Education", s_cell_small), Paragraph(f"{_safe(bd.get('education'), 0)}/15", s_cell_small)],
            [Paragraph("Formatting", s_cell_small), Paragraph(f"{_safe(bd.get('formatting'), 0)}/10", s_cell_small)],
            [Paragraph("Keyword Density", s_cell_small), Paragraph(f"{_safe(bd.get('keyword_density'), 0)}/15", s_cell_small)],
        ]
        t2 = Table(bd_rows, colWidths=[70*mm, 30*mm])
        t2.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(t2)
        story.append(Spacer(1, 3))
        matched = ats_score.get("matched_keywords") or []
        missing = ats_score.get("missing_keywords") or []
        if matched:
            story.append(Paragraph(f"<b>Matched keywords:</b> {', '.join([_safe(k) for k in matched[:8]])}", s_small))
        if missing:
            story.append(Paragraph(f"<b>Missing keywords:</b> {', '.join([_safe(k) for k in missing[:8]])}", s_small))
        # Style missing vs matched via text only (color not critical for PDF)
        story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("ATS Resume Score: Not available (no resume or JD provided)", s_small))
        story.append(Spacer(1, 4))

    # ── Interview Summary ──
    story.append(Paragraph("Interview Summary", s_h1))
    total_q = _safe(session_data.get("total_questions") or session_data.get("total") or len(session_data.get("questions", [])) if isinstance(session_data.get("questions"), list) else 0, 0)
    # Try to get avg scores from session_data or candidate_data or top-level report dict
    def _get_score(key):
        for src in (session_data, candidate_data):
            if isinstance(src, dict) and key in src:
                return src.get(key)
        return None

    # If candidate_data actually is the full report dict, fallback
    overall = _safe(_get_score("overall_score") or _get_score("avg_overall") or 0, 0)
    tech = _safe(_get_score("technical_score") or _get_score("avg_technical") or 0, 0)
    comm = _safe(_get_score("communication_score") or _get_score("avg_communication") or 0, 0)
    conf = _safe(_get_score("confidence_score") or _get_score("avg_confidence") or 0, 0)
    # Also try report-level keys if candidate_data contains them (when caller passes report dict)
    # The caller will pass candidate_data=report.candidate_info etc., so we accept flexible

    summ_rows = [
        [Paragraph("<b>Metric</b>", s_cell), Paragraph("<b>Value</b>", s_cell)],
        [Paragraph("Total Questions", s_cell_small), Paragraph(str(total_q), s_cell_small)],
        [Paragraph("Overall Score", s_cell_small), Paragraph(f"{overall}/10", s_cell_small)],
        [Paragraph("Technical", s_cell_small), Paragraph(f"{tech}/10", s_cell_small)],
        [Paragraph("Communication", s_cell_small), Paragraph(f"{comm}/10", s_cell_small)],
        [Paragraph("Confidence", s_cell_small), Paragraph(f"{conf}/10", s_cell_small)],
    ]
    # Add extra scores if present
    for extra_key, label in [("problem_solving_score", "Problem Solving"), ("time_management_score", "Time Management"), ("conceptual_clarity_score", "Conceptual Clarity")]:
        val = _get_score(extra_key)
        if val is not None:
            summ_rows.append([Paragraph(label, s_cell_small), Paragraph(f"{val}/10", s_cell_small)])
    t3 = Table(summ_rows, colWidths=[70*mm, 30*mm])
    t3.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(t3)
    story.append(Spacer(1, 4))

    # ── Skill Gaps / Recommendations ──
    skill_gaps = session_data.get("skill_gaps") or candidate_data.get("skill_gaps") or []
    recommendations = session_data.get("recommendations") or candidate_data.get("recommendations") or []
    # Also support report dict passed as candidate_data
    if not skill_gaps and isinstance(candidate_data, dict) and "skill_gaps" in candidate_data:
        skill_gaps = candidate_data.get("skill_gaps", [])
    if not recommendations and isinstance(candidate_data, dict) and "recommendations" in candidate_data:
        recommendations = candidate_data.get("recommendations", [])

    if skill_gaps:
        story.append(Paragraph("Skill Gaps", s_h2))
        for gap in skill_gaps[:6]:
            if isinstance(gap, dict):
                skill = _safe(gap.get("skill") or gap.get("area"), "Skill")
                level = _safe(gap.get("level") or gap.get("priority"), "medium")
                desc = _truncate(gap.get("gap") or gap.get("gap_description") or gap.get("description") or "", 300)
                rec = _truncate(gap.get("recommendation") or gap.get("description") or "", 250)
                story.append(Paragraph(f"<b>{skill}</b> ({level}) — {desc}", s_body))
                if rec and rec != desc:
                    story.append(Paragraph(f"<i>Rec:</i> {rec}", s_small))
            else:
                story.append(Paragraph(_truncate(str(gap), 300), s_body))
        story.append(Spacer(1, 3))

    if recommendations:
        story.append(Paragraph("Recommendations", s_h2))
        for rec in recommendations[:6]:
            if isinstance(rec, dict):
                area = _safe(rec.get("area") or rec.get("skill"), "General")
                desc = _truncate(rec.get("description") or rec.get("recommendation") or "", 300)
                prio = _safe(rec.get("priority"), "medium")
                story.append(Paragraph(f"<b>{area}</b> [{prio}] — {desc}", s_body))
            else:
                story.append(Paragraph(_truncate(str(rec), 300), s_body))
        story.append(Spacer(1, 3))

    # ── Per-question breakdown ──
    answers = session_data.get("answers") or candidate_data.get("answers") or []
    # If report dict passed as whole, answers may be there
    if not answers and isinstance(candidate_data, dict) and "answers" in candidate_data:
        answers = candidate_data.get("answers", [])
    if answers:
        story.append(Paragraph("Per-Question Breakdown", s_h1))
        for idx, qa in enumerate(answers[:20], 1):
            if not isinstance(qa, dict):
                continue
            q = _truncate(qa.get("question") or qa.get("q") or f"Question {idx}", 400)
            a = _truncate(qa.get("answer") or qa.get("response") or qa.get("text") or "", 600)
            score = _safe(qa.get("overall_score") or qa.get("score") or qa.get("avg_overall") or 0, 0)
            fb = _truncate(qa.get("feedback") or qa.get("score_explanation") or qa.get("improved_answer") or "", 500)
            story.append(Paragraph(f"<b>Q{idx}:</b> {q}", s_body))
            story.append(Paragraph(f"<b>A{idx}:</b> {a}", s_small))
            story.append(Paragraph(f"<b>Score:</b> {score}/10" + (f" — <i>{fb}</i>" if fb and fb != "N/A" else ""), s_small))
            story.append(Spacer(1, 2))
            # Light separator
            story.append(HRFlowable(width="100%", thickness=0.4, color=colors.HexColor("#e2e8f0"), spaceAfter=4))
    else:
        story.append(Paragraph("No per-question data available for this session.", s_small))
        story.append(Spacer(1, 4))

    # ── Footer ──
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#e2e8f0"), spaceAfter=6))
    story.append(Paragraph(f"Generated by AI Interview Intelligence System — {now_str}", PS("Footer", parent=s_small, alignment=TA_CENTER, textColor=colors.HexColor("#94a3b8"))))
    story.append(Paragraph("This report is auto-generated for preparation purposes. Scores are indicative.", PS("Footer2", parent=s_small, alignment=TA_CENTER, fontSize=6.5, textColor=colors.HexColor("#94a3b8"))))

    # Build
    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 6.5)
        canvas.setFillColor(colors.HexColor("#94a3b8"))
        canvas.drawCentredString(A4[0] / 2, 12 * mm, f"AI Interview Intelligence System • {now_str} • Page {doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    buf.seek(0)
    return buf
